###################################################################################################
# Description: Playbook to install and configure MapR Cluster with Core Services and all the Hadoop ecosystem components
# OS Dependency:
# Role Dependency:
# Author: Anwar Adil ; aadil@mapr.com
# ##################################################################################################



#- hosts: mapr
#  become: yes
#  become_user: root
#  tasks:
    
#     - name: maprtech.repo 
#       template: src=./templates/maprtech.repo  dest=/etc/yum.repos.d/maprtech.repo mode=0644 owner=root group=root


#     - name: yum repolist
#       shell: yum repolist
  
- hosts: zookeepers
  become: yes
  tasks:
    - name: install mapr-zookeeper
      yum: name=mapr-zookeeper state=present


## Play to install and configure CLDB
- hosts: cldb
  become: yes
  tasks:
    - name: install mapr-cldb packages
      yum: name=mapr-cldb state=present


## Play to install and configure ResourceManager
- hosts: resourcemanager
  become: yes
  tasks:
    - name: install mapr-resourcemanager
      yum: name=mapr-resourcemanager state=present

    #- name: check whether warden is running
    #  command: service mapr-warden status
    #  register: warden_status
    #  failed_when: warden_status.rc not in (0,1)


## Play to install and configure HistoryServer
- hosts: historyserver
  become: yes
  tasks:
    - name: install historyserver
      yum: name=mapr-historyserver state=present


## Play to install and configure NodeManager
- hosts: all
  become: yes
  tasks:
    - name: install mapr-nodemanager packages
      yum: name=mapr-nodemanager state=present


## Play to install and configure WebServer
- hosts: webserver
  become: yes
  tasks:
    - name: install mapr-webserver packages
      yum: name=mapr-webserver state=present


## Play to install and configure NFS
- hosts: all
  become: yes
  tasks:
    - name: install mapr-nfs packages
      yum: name=mapr-nfs state=present


## Play to install and configure FileServer
- hosts: all
  become: yes
  tasks:
    - name: install mapr-fileserver
      yum: name=mapr-fileserver state=present

- hosts: all
  become: yes
  tasks:
    - name: java_home
      #command: sed -i "'s/#export JAVA_HOME=/export JAVA_HOME=\/usr\/lib\/jvm\/java-1.7.0-openjdk-1.7.0.85-2.6.1.2.el7_1.x86_64\/jre/g' /opt/mapr/conf/env.sh"
      #lineinfile: dest=/opt/mapr/conf/env.sh regexp=^#export JAVA_HOME= line="export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.102-1.b14.el7_2.x86_64/jre"
      action: lineinfile dest=/opt/mapr/conf/env.sh regexp='#export JAVA_HOME.*' line='export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.102-1.b14.el7_2.x86_64/jre'
